spring:
  application:
    name: devpilot-ai

  datasource:
    url: jdbc:postgresql://{datasource.host}:${datasource.port}/${datasource.database-name}
    username: ${datasource.user}
    password: ${datasource.password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        formal-sql: true

server:
  port: 8080